[package]
authors = ["The Rust Project Developers"]
name = "panic_abort"
version = "0.0.0"
edition = "2018"

[lib]
path = "lib.rs"
test = false
bench = false
doc = false

[dependencies]
core = { path = "../libcore" }
libc = { path = "../../../no_std_test/skyline/skyline_libc", features = ["rustc-dep-of-std"] }
compiler_builtins = "0.1.0"
